"Vundle plugin manager
set nocompatible              
filetype off                  
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
    Plugin 'VundleVim/Vundle.vim'
    Plugin 'vim-airline/vim-airline'
    Plugin 'vim-airline/vim-airline-themes'
    Plugin 'morhetz/gruvbox'
    Plugin 'Valloric/YouCompleteMe'
call vundle#end()
filetype plugin indent on   
filetype plugin on

Plugin 'emmet-vim'


source ~/.vcomments.vim

"Colors
syntax enable



"Spaces & Tabs
set tabstop=2
set softtabstop=2
set expandtab
set cindent
set shiftwidth=4
set autoindent
set formatoptions+=w
set tw=80

" make backspace work
set backspace=2 
set backspace=indent,eol,start


"GUI config
set showcmd
set lazyredraw
set showmatch
set background=dark
colorscheme gruvbox 
let g:airline_theme='gruvbox'
let g:airline_powerline_fonts = 1
let g:ycm_path_to_python_interpreter = '/usr/bin/python'
let g:ycm_global_ycm_extra_conf = '~/.vim/bundle/YouCompleteMe/third_party/ycmd/.ycm_extra_conf.py'




"Shortcuts
inoremap jk <esc>
inoremap JK <esc>



"Auto close brackets
function! s:CloseBracket()
    let line = getline('.')
    if line =~# '^\s*\(struct\|class\|enum\) '
        return "{\<Enter>};\<Esc>O"
    elseif searchpair('(', '', ')', 'bmn', '', line('.'))
        " Probably inside a function call. Close it off.
        return "{\<Enter>});\<Esc>O"
    else
        return "{\<Enter>}\<Esc>O"
    endif
endfunction
inoremap <expr> {<Enter> <SID>CloseBracket()



"Misc
set number
"set relativenumber
set noundofile
set mouse=a
set hlsearch
hi Search ctermfg=DarkCyan
set incsearch


"Matchit
packadd! matchit
